#ifndef SMTPMIME_GLOBAL_H
#define SMTPMIME_GLOBAL_H

#if defined(SMTP_MIME_LIBRARY_STATIC)
# define SMTP_MIME_EXPORT
#elif defined(SMTP_MIME_LIBRARY)
# define SMTP_MIME_EXPORT Q_DECL_EXPORT
#else
# define SMTP_MIME_EXPORT Q_DECL_IMPORT
#endif

#endif // SMTPMIME_GLOBAL_H
